//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SustavZaVodjenjeRadnika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administratori
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        [Display(Name = "Lozinka")]
        public string lozinka { get; set; }
        [Display(Name = "Korisnicko ime")]
        public string korisnicko_ime { get; set; }
    }
}
