//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustavZaVodjenjeRadnika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanovi_projekta
    {
        public int zaposlenik_id { get; set; }
        public int projekt_id { get; set; }
    
        public virtual Projekti Projekti { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
    }
}
