//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SustavZaVodjenjeRadnika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekti()
        {
            this.Clanovi_projekta = new HashSet<Clanovi_projekta>();
            this.Zadaci = new HashSet<Zadaci>();
        }
        [Display(Name = "Naziv projekta")]
        public int id { get; set; }
        [Display(Name = "Naziv projekta")]
        public string naziv { get; set; }
        [Display(Name = "Opis projekta")]
        public string opis { get; set; }
        [Display(Name = "Status projekta")]
        public bool status { get; set; }
        [Display(Name = "Pocetno vrijeme")]
        public Nullable<System.DateTime> start_on { get; set; }
        [Display(Name = "Naziv odjela")]
        public int odjel_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clanovi_projekta> Clanovi_projekta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadaci> Zadaci { get; set; }
    }
}
