//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustavZaVodjenjeRadnika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satnica
    {
        public int zaposlenik_id { get; set; }
        public int mjesec_id { get; set; }
        public double iznos { get; set; }
        public double iznos_kn { get; set; }
    
        public virtual Mjesec Mjesec { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
    }
}
