//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustavZaVodjenjeRadnika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vremenska_lista_zadataka
    {
        public int id { get; set; }
        public int projekt_id { get; set; }
        public int zaposlenik_id { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.TimeSpan> sati { get; set; }
        public string opis { get; set; }
        public int id_zadatka { get; set; }
    
        public virtual Zadaci Zadaci { get; set; }
    }
}
